---
title: "Week06b_lecturescript"
author: "Megan Smith"
date: '2024-10-08'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE,
                      fig.path = "../output/")
```

## Lecture 6b: Cont RMarkdown

## Load libraries
```{r}
library(palmerpenguins)
library(here)
library(tidyverse)
library(kableExtra)
```


## create penguin plot
```{r,penguinplot,out.width="70%", fig.cap="This is a scatter plot",dev="pdf"}
penguins %>% 
  ggplot(aes(x=bill_length_mm,
             y=bill_depth_mm,
             color=species)) +
  geom_point()+
  geom_smooth(method='lm')+
  labs(x ="Bill Length (mm)",
       y= "Bill Depth (mm)",)+
  theme_bw()
```

## creating a table

| Time  | Session | Topic    |
|:------|:-------:|---------:|
| _left_ | _center_| _right_ |
| 01:00  | 1       | Anatomy |
| 01:50  |         | *Break* |
| 02:00  | 2       | Tables  |
| 02:45  |         | *Break* |



```{r}
penguins %>%
  group_by(species) %>%
  summarise(billmean = mean(bill_length_mm, na.rm = TRUE)) %>%
  kbl() %>% # make it a kable table
  kable_classic()%>%
  row_spec(2, bold = T, color = "white", background = "red") %>% 
  kable_styling(full_width = FALSE)
```

