---
title: "Week09bHomework"
author: "Megan Smith"
date: "2024-10-30"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE,
                      fig.path = "../output/")
```

Below is the code and figures for Week 9b Homework

# Load Libraries
```{r}
library(tidyverse)
library(here)
library(janitor)
```

# Load in data 
```{r}
intide_data<- read_csv(here("Week_09", "data", "intertidaldata.csv"))

```
# Inspect Data 
```{r}
glimpse(intide_data)
```
# Clean Data 
```{r}
intide_clean<-intide_data %>% # cleaning column and  quadrat names
  clean_names() %>% # using the janitor package to clean column names
  mutate(quadrat = str_replace(quadrat, "^(Low|Mid|High).*", "\\1")) #trying to use regex more often
head(intide_clean)

```
# Selecting sampling locations 
```{r}
selectsites<-intide_clean %>% 
  filter(site %in% c("Starfish Point", "Pyramid Point", "Fogarty Creek", "Cape Meares")) %>% # these had over 100 total organisms
  pivot_longer(cols= whelks_counts:stars_counts, #pivoting longer to add all organisms
               names_to = "Organisms",
               values_to = "Values") %>% 
  group_by(site, Organisms, quadrat) %>% 
  mutate(quadrat = factor(quadrat, levels= c("Low", "Mid", "High"))) %>%  # making low, medium and high factors 
  summarise(Total_Organisms = sum(Values, na.rm= TRUE))# summarizing total organisms 
```

# Creating a plot 
```{r Total_Organism_Plot, fig.cap="Total Organism Counts"}
ggplot(selectsites, aes(x = Total_Organisms, y=quadrat, fill= quadrat)) +
  geom_bar(stat = "identity") +  # barplot to show total organisms 
  labs(title = "Total Organism Counts by Site and Tide",
       subtitle = "Organisms Include: Whelks, Crabs, Sea Stars",
       x = "Site",
       y = "Total Organisms",
       fill= "Tide") +
  scale_fill_manual(values= c("#48cae4", "#0077B6","#03045E"))+ # selecting colors
  theme_minimal() +
  theme(legend.position = "right",  
        axis.text.x = element_blank()) + #removing x axis for clarity
  coord_flip() + #flipping the axis
  facet_wrap(~ site, scales= "free") # faceting by site and making scales free for clarity
```

