---
title: "Week13 Homework"
author: "Megan Smith"
date: "2024-12-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(here)
library(tidyverse)
```

Read in data Loop version

Pre-allocate space for loop
```{r}
hwdata<-here("Week_13", "data", "homework")
files <- dir(path = hwdata,pattern = ".csv")
hw_data<-tibble(filename =  rep(NA, length(files)),  # column name for year
                  mean_temp = rep(NA, length(files)), # column name for the mean temperature
                sd_temp = rep(NA, length(files)), # column name for sd temp
                  mean_intens = rep(NA, length(files)), # column name for the mean intensity
                 sd_intens = rep(NA, length(files)), # column name for sd intensity 
) # column name for the year name
hw_data
```

```{r}
for (i in 1:length(files)){ # loop over 1:3 the number of files 
  raw_data<-read_csv(paste0(hwdata,"/",files[i]))
  hw_data$filename[i]<-files[i]
  hw_data$mean_temp[i]<-mean(raw_data$Temp.C, na.rm =TRUE) 
  hw_data$sd_temp[i] <- sd(raw_data$Temp.C, na.rm = TRUE)
  hw_data$mean_intens[i]<-mean(raw_data$Intensity.lux, na.rm =TRUE)
  hw_data$sd_intens[i] <- sd(raw_data$Intensity.lux, na.rm = TRUE)
} 
hw_data
```


Purr method 
```{r}
PathHW <- here("Week_13", "data", "homework")

# List CSV files in that folder
fileshw <- dir(path = PathHW, pattern = ".csv", full.names = TRUE)
```

```{r}
datahw <- fileshw %>%
  set_names() %>%  # Set file names as IDs
  map_df(read_csv, .id = "filename") %>%  # Read files and bind them into a single dataframe
  group_by(filename) %>%  # Group by file name
  summarise(
    mean_temp = mean(Temp.C, na.rm = TRUE),
    sd_temp = sd(Temp.C, na.rm = TRUE),  
    mean_intens = mean(Intensity.lux, na.rm = TRUE),
    sd_intens = sd(Intensity.lux, na.rm = TRUE)
  )
datahw
```

